{{- if .Values.gatewayApi.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "ricochet.fullname" . }}
  labels:
    {{- include "ricochet.labels" . | nindent 4 }}
    {{- with .Values.gatewayApi.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gatewayApi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ required "gatewayApi.gateway.name is required when gatewayApi.enabled=true" .Values.gatewayApi.gateway.name }}
      {{- if .Values.gatewayApi.gateway.namespace }}
      namespace: {{ .Values.gatewayApi.gateway.namespace }}
      {{- end }}
  {{- with .Values.gatewayApi.hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.gatewayApi.rules }}
    - {{- if .matches }}
      matches:
        {{- range .matches }}
        - {{- if .path }}
          path:
            type: {{ .path.type }}
            value: {{ .path.value }}
          {{- end }}
          {{- if .headers }}
          headers:
            {{- toYaml .headers | nindent 12 }}
          {{- end }}
          {{- if .queryParams }}
          queryParams:
            {{- toYaml .queryParams | nindent 12 }}
          {{- end }}
          {{- if .method }}
          method: {{ .method }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if .filters }}
      filters:
        {{- toYaml .filters | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ include "ricochet.fullname" $ }}
          port: {{ $.Values.service.port }}
          {{- if .weight }}
          weight: {{ .weight }}
          {{- end }}
    {{- end }}
{{- end }}
