{{- if .Values.serviceAccount.create -}}
{{- $annotations := .Values.serviceAccount.annotations | default dict -}}
{{- if .Values.openshift.scc.annotate -}}
{{- $annotations = merge (dict "openshift.io/scc" .Values.openshift.scc.name) $annotations -}}
{{- end -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ricochet.serviceAccountName" . }}
  labels:
    {{- include "ricochet.labels" . | nindent 4 }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
{{- end }}
